export const CHECK_AUTENTIFICATION = 'CHECK_AUTENTIFICATION';
export const CHECK_AUTENTIFICATION_PROCESS = 'CHECK_AUTENTIFICATION_PROCESS';

export const USERNAME_CHANGE = 'USERNAME_CHANGE';
export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';

export const LOADING_LOGIN_FORM = 'LOADING_LOGIN_FORM';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';