export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL';
export const GET_ALL_USERS_PROCESS = 'GET_ALL_USERS_PROCESS';

export const GET_ALL_TODOS_PROCESS = 'GET_ALL_TODOS_PROCESS';
export const GET_ALL_TODOS_SUCCESS = 'GET_ALL_TODOS_SUCCESS';
export const GET_ALL_TODOS_FAIL = 'GET_ALL_TODOS_FAIL';

export const GET_TODO_PROCESS = 'GET_TODO_PROCESS';
export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS';
export const GET_TODO_FAIL = 'GET_TODO_FAIL'; 

export const TODO_TITLE_CHANGE = 'TODO_TITLE_CHANGE';
export const TODO_DESCRIPTION_CHANGE = 'TODO_DESCRIPTION_CHANGE';

export const SAVE_TODO_PROCESS = 'SAVE_TODO_PROCESS';
export const SAVE_TODO_SUCCESS = 'SAVE_TODO_SUCCESS';
export const SAVE_TODO_FAIL = 'SAVE_TODO_FAIL';

export const REMOVE_TODO_PROCESS = 'REMOVE_TODO_PROCESS';
export const REMOVE_TODO_FAIL = 'REMOVE_TODO_FAIL'; // todo сообщение об ошибке загрузки