export const ACTION_TYPES = {
    CHECK_AUTENTIFICATION: 'CHECK_AUTENTIFICATION',
    CHECK_AUTENTIFICATION_PROCESS: 'CHECK_AUTENTIFICATION_PROCESS',

    USERNAME_CHANGE: 'USERNAME_CHANGE',
    PASSWORD_CHANGE: 'PASSWORD_CHANGE',

    LOADING_LOGIN_FORM: 'LOADING_LOGIN_FORM',

    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    LOGOUT: 'LOGOUT',

    GET_ABOUT_ME: 'GET_ABOUT_ME',
    GET_ABOUT_ME_LOADING: 'GET_ABOUT_ME_LOADING',
    GET_ABOUT_ME_SUCCESS: 'GET_ABOUT_ME_SUCCESS'
};