export const ACTION_TYPES = {
    GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_FAIL: 'GET_ALL_USERS_FAIL',
    GET_ALL_USERS_PROCESS: 'GET_ALL_USERS_PROCESS',

    GET_ABOUT_ME_PROCESS: 'GET_ABOUT_ME_PROCESS',
    GET_ABOUT_ME_SUCCESS: 'GET_ABOUT_ME_SUCCESS',
    GET_ABOUT_ME_FAIL: 'GET_ABOUT_ME_FAIL',

    GET_ALL_TODOS_PROCESS: 'GET_ALL_TODOS_PROCESS',
    GET_ALL_TODOS_SUCCESS: 'GET_ALL_TODOS_SUCCESS',
    GET_ALL_TODOS_FAIL: 'GET_ALL_TODOS_FAIL',

    GET_TODO_PROCESS: 'GET_TODO_PROCESS',
    GET_TODO_SUCCESS: 'GET_TODO_SUCCESS',
    GET_TODO_FAIL: 'GET_TODO_FAIL', 

    TODO_TITLE_CHANGE: 'TODO_TITLE_CHANGE',
    TODO_DESCRIPTION_CHANGE: 'TODO_DESCRIPTION_CHANGE',

    SAVE_TODO_PROCESS: 'SAVE_TODO_PROCESS',
    SAVE_TODO_SUCCESS: 'SAVE_TODO_SUCCESS',
    SAVE_TODO_FAIL: 'SAVE_TODO_FAIL',

    REMOVE_TODO_PROCESS: 'REMOVE_TODO_PROCESS',
    REMOVE_TODO_FAIL: 'REMOVE_TODO_FAIL', // todo сообщение об ошибке загрузки
};