export const ACTION_TYPES = {
    CHECK_AUTENTIFICATION: 'CHECK_AUTENTIFICATION',
    CHECK_AUTENTIFICATION_PROCESS: 'CHECK_AUTENTIFICATION_PROCESS',

    USERNAME_CHANGE: 'USERNAME_CHANGE',
    PASSWORD_CHANGE: 'PASSWORD_CHANGE',

    LOADING_LOGIN_FORM: 'LOADING_LOGIN_FORM',

    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    LOGOUT: 'LOGOUT',

    GET_ABOUT_ME_PROCESS: 'GET_ABOUT_ME_PROCESS',
    GET_ABOUT_ME_LOADING: 'GET_ABOUT_ME_LOADING',
    GET_ABOUT_ME_SUCCESS: 'GET_ABOUT_ME_SUCCESS',

    GET_ALL_TODOS_PROCESS: 'GET_ALL_TODOS_PROCESS',
    GET_ALL_TODOS_SUCCESS: 'GET_ALL_TODOS_SUCCESS',
    GET_ALL_TODOS_FAIL: 'GET_ALL_TODOS_FAIL', // todo сообщение об ошибке загрузки

    GET_TODO_PROCESS: 'GET_TODO_PROCESS',
    GET_TODO_SUCCESS: 'GET_TODO_SUCCESS',
    GET_TODO_FAIL: 'GET_TODO_FAIL', // todo сообщение об ошибке загрузки

    TODO_TITLE_CHANGE: 'TODO_TITLE_CHANGE',
    TODO_DESCRIPTION_CHANGE: 'TODO_DESCRIPTION_CHANGE',

    SAVE_TODO_PROCESS: 'SAVE_TODO_PROCESS',
    SAVE_TODO_SUCCESS: 'SAVE_TODO_SUCCESS',
    SAVE_TODO_FAIL: 'SAVE_TODO_FAIL', // todo сообщение об ошибке загрузки
};